openapi: 3.0.0
info:
  version: '1.1.0'
  title: 'Default Route Configuration APIs'
  description: |
    Release Date: 2019/10/02
    Default Route Configuration APIs

components:
  schemas:
    RouteInformation:
      title: Device route configuration
      properties:
        default:
          type: string
          description: default route display name.
          readOnly: true
        priorityList:
          type: array
          items:
            type: string
            pattern: '[A-Za-z0-9_-]+'
            minLength: 2
            maxLength: 15
    WANInformation:
      title: Current WAN information
      properties:
        name:
          type: string
          description: Interface name.
        displayName:
          type: string
          description: Interface display name.
        ip:
          type: string
          description: IP address for the Ethernet interface.
        netmask:
          type: string
          description: Interface netmask.
        gateway:
          type: string
          description: Gateway is a router or a proxy server that routes between networks.
        dns:
          type: array
          description: |
            The Domain Name System (DNS) is a hierarchical distributed naming
            system for computers, services, or any resource connected to the
            Internet or a private network.
          items:
            type: string

paths:
  /device/route:
    get:
      description: Get device route configuration.
      tags: ["device", "route"]
      responses:
        200:
          description: Device route configuration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouteInformation'
              example:
                data:
                  type: route
                  default: LAN1
                  priorityList:
                    - LAN1
                    - Cellular1
                    - LAN2
    patch:
      tags: ["device", "route"]
      description: Update device route configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteInformation'
            example:
              priorityList:
                - LAN2
                - Cellular1
                - LAN1
      responses:
        200:
          description: Device route configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouteInformation'
              example:
                data:
                  type: route
                  default: LAN2
                  priorityList:
                    - LAN2
                    - Cellular1
                    - LAN1
  /device/network/wan:
    get:
      description: Get device route configuration of wan.
      tags: ["device", "network", "wan"]
      responses:
        200:
          description: Device route configuration of wan.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WANInformation'
              example:
                data:
                  name: eth0
                  displayName: LAN1
                  ip: 192.168.3.127
                  netmask: 255.255.255.0
                  gateway: 192.168.3.254
                  dns:
                  - 192.168.3.1
